{
 "title": "MOD1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# MOD1" } },
  { "title": "Ubication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "title": "Ubication", "type": "geomap", "gridPos": { "h": 10, "w": 21, "x": 0, "y": 3 } },
  { "title": "Local time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 } },
  {
   "title": " Altitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "159" }
   ]
  },
  { "title": "Real time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Humity",
   "type": "gauge",
   "description": "Humity",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "description": "Pressure",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pressure" }
   ]
  },
  {
   "title": "Luminosity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "luminosity" }
   ]
  },
  {
   "title": "Windspeed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "windspeed" }
   ]
  },
  {
   "title": "UV",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uv" }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "co2" }
   ]
  },
  {
   "title": "Pm1_0",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm1_0" }
   ]
  },
  {
   "title": "Pm10",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm10" }
   ]
  },
  {
   "title": "Pm2_5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pm2_5" }
   ]
  },
  { "title": "Historical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Humity",
   "type": "timeseries",
   "description": "Humity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "targets": [
    { "expr": "humidity" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "description": "Pressure",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    { "expr": "pressure" }
   ]
  }
 ]
}